"""The `KbType` contract every knowledge-base entry type implements."""

from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import PurePosixPath
from typing import ClassVar, Literal, get_args

from pydantic import BaseModel, ConfigDict

from cartograph.kb.slug import slugify
from cartograph.kb.views import KbEntryView

#: Which physical columns a type answers `kb_lookup` on. Deliberately a closed
#: set of column names, not JSONB paths: tier 1 of the lookup contract must be
#: an equality probe against a *unique* index, and no partial unique index can
#: cover an element of a JSONB array.
LookupKey = Literal["title", "slug", "aliases"]

LOOKUP_KEYS: tuple[str, ...] = get_args(LookupKey)

#: Every generated file opens with this. Slice 17's exporter uses the prefix to
#: recognize its own output when the manifest is missing.
MARKER_PREFIX = "<!-- generated by cartograph;"


@dataclass(frozen=True, slots=True)
class ExportContext:
    """Repo-level facts a *type* cannot invent from a list of entries.

    `CONTEXT.md` opens with an H1 and a description of the context itself;
    those belong to the repository, not to any glossary term.
    """

    repository_name: str
    context_name: str
    context_description: str = ""

    def marker(self, type_name: str, slug: str | None = None) -> str:
        source = f"{type_name}/{slug}" if slug else type_name
        return (
            f"{MARKER_PREFIX} edits will be overwritten. source: kb {source} -->"
        )


class KbType(ABC):
    """A knowledge-base entry type.

    Classmethods on classes rather than instances: there is no per-instance
    state, and `Glossary.Payload` / `Glossary.export(...)` read naturally.
    """

    name: ClassVar[str]
    label: ClassVar[str]
    lookup_keys: ClassVar[tuple[LookupKey, ...]] = ("title",)
    assigns_seq: ClassVar[bool] = False
    #: None means a repo-root artifact (glossary -> CONTEXT.md).
    export_dir: ClassVar[str | None] = None

    class Payload(BaseModel):
        model_config = ConfigDict(extra="forbid")

    # ---- validation -----------------------------------------------------

    @classmethod
    def validate_payload(cls, raw: dict | None) -> dict:
        """Parse and normalize; raises pydantic.ValidationError."""
        return cls.Payload.model_validate(raw or {}).model_dump(mode="json")

    @classmethod
    def payload_fields(cls) -> dict[str, str]:
        """`{field: "type, required|optional"}` — the self-documenting half of
        the error an agent gets back from a rejected `kb_propose` payload."""
        fields: dict[str, str] = {}
        for field_name, field in cls.Payload.model_fields.items():
            annotation = field.annotation
            type_name = getattr(annotation, "__name__", None) or str(annotation)
            state = "required" if field.is_required() else "optional"
            fields[field_name] = f"{type_name}, {state}"
        return fields

    @classmethod
    def validate_entry(cls, view: KbEntryView) -> list[str]:
        """Non-fatal lint surfaced by the API and the export CLI.

        Never blocks a write — a KB you cannot save to is a KB nobody uses.
        """
        return []

    # ---- derivation -----------------------------------------------------

    @classmethod
    def default_slug(cls, title: str, payload: dict) -> str:
        return slugify(title)

    @classmethod
    @abstractmethod
    def embed_text(cls, view: KbEntryView) -> str: ...

    # ---- export ---------------------------------------------------------

    @classmethod
    def sort_key(cls, view: KbEntryView) -> tuple:
        """Deterministic export ordering. The exporter sorts before calling
        `export()`, so `export()` stays pure formatting."""
        return (view.title.lower(), view.slug)

    @classmethod
    @abstractmethod
    def export(
        cls, entries: Sequence[KbEntryView], ctx: ExportContext
    ) -> dict[PurePosixPath, str]:
        """Relative path -> file content. One file per entry, or one file for
        all of them (glossary) — the mapping is what lets a type choose."""


# ---- shared rendering helpers -------------------------------------------


def render(lines: list[str]) -> str:
    """Join rendered lines with LF and exactly one trailing newline."""
    return "\n".join(lines).rstrip("\n") + "\n"


def section(lines: list[str], heading: str, text: str) -> None:
    """Append `## heading` + body, or nothing when the body is empty."""
    body = (text or "").strip()
    if body:
        lines += [f"## {heading}", "", body, ""]


def bullets(lines: list[str], heading: str, items: Sequence[str]) -> None:
    kept = [item for item in items if str(item).strip()]
    if kept:
        lines += [f"## {heading}", ""]
        lines += [f"- {item}" for item in kept]
        lines.append("")


def file_path(type_cls: type[KbType], stem: str) -> PurePosixPath:
    directory = type_cls.export_dir
    return PurePosixPath(directory) / f"{stem}.md" if directory else PurePosixPath(f"{stem}.md")
