"""typed kb

Turns the flat knowledge_base table into a typed store (slice 15).

DOWNGRADE IS LOSSY. The pre-typed schema has no representation for a
specification, decision, convention or runbook, and none for an entry that is
not published — so downgrade() DELETES every row that is not a published
glossary entry. It reports the count it removed before doing so.

Written by hand rather than autogenerated: alembic cannot reproduce the
expression-based partial unique indexes this table needs.

Revision ID: b7e3c1a4d92f
Revises: 64f9f7a7d426
Create Date: 2026-08-18

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b7e3c1a4d92f"
down_revision: Union[str, None] = "64f9f7a7d426"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Kept in lockstep with cartograph.kb.slug.slugify — pinned by
# tests/kb/test_migration.py::test_slugify_matches_migration_regex.
SLUG_SQL = (
    "nullif(trim(both '-' from "
    "regexp_replace(lower(term), '[^a-z0-9]+', '-', 'g')), '')"
)


def upgrade() -> None:
    # 1. every new column nullable and default-free, so the backfill decides
    #    the values rather than the DDL
    op.add_column("knowledge_base", sa.Column("type", sa.Text(), nullable=True))
    op.add_column("knowledge_base", sa.Column("slug", sa.Text(), nullable=True))
    op.add_column("knowledge_base", sa.Column("title", sa.Text(), nullable=True))
    op.add_column("knowledge_base", sa.Column("body", sa.Text(), nullable=True))
    op.add_column(
        "knowledge_base",
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("knowledge_base", sa.Column("status", sa.Text(), nullable=True))
    op.add_column("knowledge_base", sa.Column("review_note", sa.Text(), nullable=True))
    op.add_column("knowledge_base", sa.Column("seq", sa.Integer(), nullable=True))
    op.add_column("knowledge_base", sa.Column("repository_id", sa.BigInteger(), nullable=True))
    op.add_column("knowledge_base", sa.Column("source", sa.Text(), nullable=True))
    op.add_column("knowledge_base", sa.Column("created_by", sa.Text(), nullable=True))
    op.add_column(
        "knowledge_base",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    )

    # 2. backfill. Plain SQL, not the ORM — the model has already moved on.
    #    Every legacy row is a global glossary term, which is the correct read
    #    of a table that had no type and no repository scope.
    op.execute(
        """
        UPDATE knowledge_base SET
            type       = 'glossary',
            title      = term,
            body       = definition,
            status     = 'published',
            payload    = '{}'::jsonb,
            source     = 'legacy',
            created_at = updated_at
        """
    )

    # 3. slugs
    op.execute(f"UPDATE knowledge_base SET slug = {SLUG_SQL}")
    op.execute("UPDATE knowledge_base SET slug = 'entry-' || id WHERE slug IS NULL")

    # 4. dedupe before the unique index exists. lower(term) was unique, but
    #    slugify is lossy — "PS-N", "PS N" and "psn" all collapse to "ps-n"/"psn".
    #
    #    A row_number() suffix is NOT enough on its own: the suffix it produces
    #    can land on a slug that already exists. "PS-N", "PS N" and "PS N 2" are
    #    all legal under the old unique lower(term) index and slugify to ps-n,
    #    ps-n, ps-n-2 — suffixing the second to "ps-n-2" collides with the third
    #    and aborts step 7 on a live table.
    #
    #    So suffix with a DOUBLE hyphen and the row's own id. The regexp above
    #    collapses every run of non-alphanumerics to a single '-', so no
    #    slugified term can ever contain '--' — which makes "<slug>--<id>"
    #    unreachable by any natural slug, and unique across rows because ids
    #    are. One pass, no collisions, and the row that legitimately owned the
    #    contested slug keeps it. (`slugify()` in cartograph.kb.slug collapses
    #    runs the same way, so entries created later cannot collide either.)
    op.execute(
        """
        WITH ranked AS (
            SELECT id, row_number() OVER (PARTITION BY slug ORDER BY id) AS rn
              FROM knowledge_base
        )
        UPDATE knowledge_base kb
           SET slug = kb.slug || '--' || kb.id
          FROM ranked r
         WHERE kb.id = r.id AND r.rn > 1
        """
    )

    # 5. lock it down
    for column in ("type", "slug", "title", "body", "status", "payload", "created_at"):
        op.alter_column("knowledge_base", column, nullable=False)
    op.alter_column("knowledge_base", "payload", server_default=sa.text("'{}'::jsonb"))
    op.alter_column("knowledge_base", "status", server_default=sa.text("'published'"))
    op.alter_column("knowledge_base", "created_at", server_default=sa.text("now()"))

    op.create_foreign_key(
        "fk_kb_repository_id",
        "knowledge_base",
        "repositories",
        ["repository_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # 6. the old shape goes
    op.drop_index("ix_kb_term_lower", table_name="knowledge_base")
    op.drop_column("knowledge_base", "term")
    op.drop_column("knowledge_base", "definition")

    # 7. the new indexes. Raw DDL: expression + partial, which op.create_index
    #    cannot express readably.
    op.execute(
        "CREATE UNIQUE INDEX ix_kb_ident ON knowledge_base "
        "(coalesce(repository_id, 0), type, lower(slug)) WHERE status = 'published'"
    )
    op.execute(
        "CREATE UNIQUE INDEX ix_kb_title_lower ON knowledge_base "
        "(coalesce(repository_id, 0), type, lower(title)) WHERE status = 'published'"
    )
    op.execute(
        "CREATE UNIQUE INDEX ix_kb_seq ON knowledge_base "
        "(coalesce(repository_id, 0), type, seq) WHERE seq IS NOT NULL"
    )
    op.create_index("ix_kb_type_status", "knowledge_base", ["type", "status"])
    op.create_index(
        op.f("ix_knowledge_base_repository_id"), "knowledge_base", ["repository_id"]
    )


def downgrade() -> None:
    # LOSSY: the old schema can hold neither a non-glossary entry nor an entry
    # that is not published — it has no `type` and no `status` column.
    #
    # Dropping unpublished rows is not optional tidying, it is required twice
    # over. (1) Keeping a rejected or proposed glossary row would strip its
    # status and review_note and leave it indistinguishable from a live term,
    # so a definition a human explicitly REJECTED would come back as fact.
    # (2) ix_kb_term_lower below is not partial, while the typed schema's
    # ix_kb_title_lower is `WHERE status='published'` — so a published entry
    # and a proposed revision of it legally share a title, and recreating the
    # old index over both would abort the downgrade halfway.
    op.execute(
        """
        DO $$
        DECLARE doomed integer;
        BEGIN
            SELECT count(*) INTO doomed FROM knowledge_base
             WHERE type <> 'glossary' OR status <> 'published';
            IF doomed > 0 THEN
                RAISE NOTICE
                    'typed_kb downgrade: deleting % entries that the pre-typed '
                    'schema cannot represent (non-glossary, or not published)',
                    doomed;
            END IF;
        END $$
        """
    )
    op.execute(
        "DELETE FROM knowledge_base WHERE type <> 'glossary' OR status <> 'published'"
    )

    op.drop_index(op.f("ix_knowledge_base_repository_id"), table_name="knowledge_base")
    op.drop_index("ix_kb_type_status", table_name="knowledge_base")
    op.execute("DROP INDEX IF EXISTS ix_kb_seq")
    op.execute("DROP INDEX IF EXISTS ix_kb_title_lower")
    op.execute("DROP INDEX IF EXISTS ix_kb_ident")
    op.drop_constraint("fk_kb_repository_id", "knowledge_base", type_="foreignkey")

    op.add_column("knowledge_base", sa.Column("term", sa.Text(), nullable=True))
    op.add_column("knowledge_base", sa.Column("definition", sa.Text(), nullable=True))
    op.execute("UPDATE knowledge_base SET term = title, definition = body")
    op.alter_column("knowledge_base", "term", nullable=False)
    op.alter_column("knowledge_base", "definition", nullable=False)
    op.create_index(
        "ix_kb_term_lower",
        "knowledge_base",
        [sa.literal_column("lower(term)")],
        unique=True,
    )

    for column in (
        "created_at", "created_by", "source", "repository_id", "seq",
        "review_note", "status", "payload", "body", "title", "slug", "type",
    ):
        op.drop_column("knowledge_base", column)
