"""The Markdown export (slice 17)."""

import hashlib
import json
from pathlib import Path

import pytest

from cartograph.kb.export.manifest import MANIFEST_NAME, read_manifest
from cartograph.kb.export.runner import run_export
from cartograph.query import ingest as q_ingest
from cartograph.query import kb as q_kb

CONTEXT = "CONTEXT.md"


@pytest.fixture
async def repo(session):
    repository = await q_ingest.upsert_repository(session, "acme", "/repos/acme")
    await session.flush()
    return repository


@pytest.fixture
async def seeded_kb(session, repo):
    await q_kb.create_entry(
        session,
        "Order",
        "A customer's request for goods.",
        payload={"avoid": ["Purchase", "transaction"]},
        repository_id=repo.id,
    )
    await q_kb.create_entry(
        session, "Invoice", "A request for payment.", repository_id=repo.id
    )
    await q_kb.create_entry(
        session,
        "Use Postgres",
        "We use Postgres.",
        type="decision",
        payload={"context": "We needed a database."},
        repository_id=repo.id,
    )
    await session.flush()
    return repo


async def export(session, repo, out, **kwargs):
    return await run_export(session, repo, Path(out), **kwargs)


# ---- happy path ----------------------------------------------------------


async def test_export_writes_context_and_adr(session, seeded_kb, tmp_path):
    result = await export(session, seeded_kb, tmp_path)
    assert result.conflicts == [] and result.failed == []

    context = (tmp_path / CONTEXT).read_text()
    assert "## Language" in context
    assert "**Order**:\nA customer's request for goods.\n_Avoid_: Purchase, transaction" in context
    assert "**Invoice**:" in context

    adr = (tmp_path / "docs/adr/0001-use-postgres.md").read_text()
    assert adr.startswith("<!-- generated by cartograph;")
    assert "# 0001. Use Postgres" in adr
    assert (tmp_path / MANIFEST_NAME).is_file()


async def test_export_is_byte_identical_on_rerun(session, seeded_kb, tmp_path):
    await export(session, seeded_kb, tmp_path)
    before = {p: p.read_bytes() for p in tmp_path.rglob("*") if p.is_file()}

    second = await export(session, seeded_kb, tmp_path)
    after = {p: p.read_bytes() for p in tmp_path.rglob("*") if p.is_file()}

    assert before == after
    assert second.written == []
    assert CONTEXT in second.unchanged


async def test_export_type_filter(session, seeded_kb, tmp_path):
    await export(session, seeded_kb, tmp_path, types=("glossary",))
    assert (tmp_path / CONTEXT).is_file()
    assert not (tmp_path / "docs").exists()


async def test_export_unknown_type_of_entry_does_not_break_the_run(
    session, seeded_kb, tmp_path
):
    bad = await q_kb.create_entry(
        session,
        "Broken",
        "…",
        type="decision",
        repository_id=seeded_kb.id,
    )
    bad.payload = {"decision_status": "maybe"}  # no longer valid for its type
    await session.flush()

    result = await export(session, seeded_kb, tmp_path)
    assert [f["slug"] for f in result.failed] == ["broken"]
    assert result.partial
    # the good files still landed
    assert (tmp_path / CONTEXT).is_file()
    assert (tmp_path / "docs/adr/0001-use-postgres.md").is_file()


# ---- clobber safety ------------------------------------------------------


async def test_export_refuses_a_handwritten_file(session, seeded_kb, tmp_path):
    handwritten = "# My own glossary\n\nDo not overwrite me.\n"
    (tmp_path / CONTEXT).write_text(handwritten)

    result = await export(session, seeded_kb, tmp_path)
    assert result.conflicts == [CONTEXT]
    assert result.partial
    assert (tmp_path / CONTEXT).read_text() == handwritten
    # the rest of the export still happened
    assert (tmp_path / "docs/adr/0001-use-postgres.md").is_file()


async def test_force_overwrites_a_handwritten_file(session, seeded_kb, tmp_path):
    (tmp_path / CONTEXT).write_text("# My own glossary\n")
    result = await export(session, seeded_kb, tmp_path, force=True)
    assert result.conflicts == []
    assert "## Language" in (tmp_path / CONTEXT).read_text()


async def test_export_detects_a_manual_edit_of_a_generated_file(
    session, seeded_kb, tmp_path
):
    await export(session, seeded_kb, tmp_path)
    target = tmp_path / "docs/adr/0001-use-postgres.md"
    target.write_text(target.read_text() + "\nHand-added paragraph.\n")

    result = await export(session, seeded_kb, tmp_path)
    assert "docs/adr/0001-use-postgres.md" in result.conflicts
    assert "Hand-added paragraph." in target.read_text()


async def test_a_lost_manifest_still_recognizes_our_own_output(
    session, seeded_kb, tmp_path
):
    await export(session, seeded_kb, tmp_path)
    (tmp_path / MANIFEST_NAME).unlink()

    # the generated-by marker on line 1 is the fallback identification
    result = await export(session, seeded_kb, tmp_path)
    assert result.conflicts == []


# ---- pruning -------------------------------------------------------------


async def test_archiving_an_entry_prunes_its_file(session, seeded_kb, tmp_path):
    await export(session, seeded_kb, tmp_path)
    adr = tmp_path / "docs/adr/0001-use-postgres.md"
    assert adr.is_file()

    entry = await q_kb.get_entry_by_slug(session, "use-postgres", type="decision")
    await q_kb.set_status(session, entry.id, "archived")
    await session.flush()

    result = await export(session, seeded_kb, tmp_path)
    assert "docs/adr/0001-use-postgres.md" in result.pruned
    assert not adr.exists()
    assert "docs/adr/0001-use-postgres.md" not in read_manifest(tmp_path)["files"]


async def test_pruning_never_deletes_an_edited_file(session, seeded_kb, tmp_path):
    await export(session, seeded_kb, tmp_path)
    adr = tmp_path / "docs/adr/0001-use-postgres.md"
    adr.write_text(adr.read_text() + "\nMine now.\n")

    entry = await q_kb.get_entry_by_slug(session, "use-postgres", type="decision")
    await q_kb.set_status(session, entry.id, "archived")
    await session.flush()

    result = await export(session, seeded_kb, tmp_path)
    assert "docs/adr/0001-use-postgres.md" in result.conflicts
    assert adr.exists() and "Mine now." in adr.read_text()


async def test_no_prune_keeps_the_file(session, seeded_kb, tmp_path):
    await export(session, seeded_kb, tmp_path)
    entry = await q_kb.get_entry_by_slug(session, "use-postgres", type="decision")
    await q_kb.set_status(session, entry.id, "archived")
    await session.flush()

    result = await export(session, seeded_kb, tmp_path, prune=False)
    assert result.pruned == []
    assert (tmp_path / "docs/adr/0001-use-postgres.md").exists()


# ---- dry run and status filtering ---------------------------------------


async def test_dry_run_writes_nothing(session, seeded_kb, tmp_path):
    result = await export(session, seeded_kb, tmp_path, dry_run=True)
    assert result.written  # it reports what it would do
    assert result.dry_run is True
    assert list(tmp_path.iterdir()) == []


async def test_export_excludes_proposed_and_rejected(session, repo, tmp_path):
    proposed = await q_kb.create_entry(
        session, "PSN", "PositageNet", status="proposed", repository_id=repo.id
    )
    rejected = await q_kb.create_entry(
        session, "DDD", "…", status="proposed", repository_id=repo.id
    )
    await q_kb.set_status(session, rejected.id, "rejected", reason="no")
    await session.flush()

    await export(session, repo, tmp_path)
    assert not (tmp_path / CONTEXT).exists()
    assert proposed.status == "proposed"


# ---- global scoping ------------------------------------------------------


async def test_global_entries_are_included_by_default(session, repo, tmp_path):
    await q_kb.create_entry(session, "PSN", "PositageNet")  # global
    await session.flush()

    await export(session, repo, tmp_path)
    assert "**PSN**:" in (tmp_path / CONTEXT).read_text()


async def test_no_include_global_excludes_them(session, repo, tmp_path):
    await q_kb.create_entry(session, "PSN", "PositageNet")
    await session.flush()

    await export(session, repo, tmp_path, include_global=False)
    assert not (tmp_path / CONTEXT).exists()


async def test_repo_entry_shadows_a_global_of_the_same_title(
    session, repo, tmp_path
):
    await q_kb.create_entry(session, "PSN", "the global expansion")
    await q_kb.create_entry(
        session, "PSN", "acme's own expansion", repository_id=repo.id
    )
    await session.flush()

    await export(session, repo, tmp_path)
    context = (tmp_path / CONTEXT).read_text()
    assert context.count("**PSN**:") == 1
    assert "acme's own expansion" in context
    assert "the global expansion" not in context


# ---- exit-code contract --------------------------------------------------


def test_partial_flags_conflicts_and_failures():
    """`partial` is what maps to exit code 3 in the CLI."""
    from cartograph.kb.export.runner import ExportResult

    assert not ExportResult("acme", written=["CONTEXT.md"]).partial
    assert ExportResult("acme", conflicts=["CONTEXT.md"]).partial
    assert ExportResult("acme", failed=[{"slug": "x", "error": "…"}]).partial


def test_cli_parser_defaults():
    from cartograph.kb.export.__main__ import build_parser

    args = build_parser().parse_args(["--repo", "acme"])
    assert args.out is None and args.types is None
    assert not args.dry_run and not args.force and not args.no_prune

    repeated = build_parser().parse_args(
        ["--repo", "acme", "--type", "glossary", "--type", "decision"]
    )
    assert repeated.types == ["glossary", "decision"]


# ---- manifest integrity (review findings 1, 5, 22, 23) -------------------


async def test_manifest_is_rewritten_even_when_nothing_changed(
    session, seeded_kb, tmp_path
):
    """A lost manifest must come back, or the marker fallback silently
    overwrites hand edits forever."""
    await export(session, seeded_kb, tmp_path)
    (tmp_path / MANIFEST_NAME).unlink()

    result = await export(session, seeded_kb, tmp_path)  # every file unchanged
    assert result.written == []
    assert (tmp_path / MANIFEST_NAME).is_file()

    # and now a hand edit is detected rather than clobbered
    target = tmp_path / "docs/adr/0001-use-postgres.md"
    target.write_text(target.read_text() + "\nMine.\n")
    after = await export(session, seeded_kb, tmp_path)
    assert "docs/adr/0001-use-postgres.md" in after.conflicts
    assert "Mine." in target.read_text()


async def test_prune_refuses_paths_outside_the_output_directory(
    session, seeded_kb, tmp_path
):
    """The manifest is repo content, so its keys are no more trusted than any
    other repo content — and pruning DELETES."""
    outside = tmp_path.parent / "victim.txt"
    outside.write_text("do not delete me\n")

    await export(session, seeded_kb, tmp_path)
    manifest = json.loads((tmp_path / MANIFEST_NAME).read_text())
    manifest["files"]["../victim.txt"] = {
        "sha256": hashlib.sha256(outside.read_bytes()).hexdigest(),
        "type": "glossary",
    }
    manifest["files"][str(tmp_path.parent / "victim.txt")] = {
        "sha256": hashlib.sha256(outside.read_bytes()).hexdigest(),
        "type": "glossary",
    }
    (tmp_path / MANIFEST_NAME).write_text(json.dumps(manifest))

    result = await export(session, seeded_kb, tmp_path)
    assert outside.exists(), "prune escaped the output directory"
    assert any("unsafe manifest path" in f["error"] for f in result.failed)


async def test_force_prunes_an_edited_file(session, seeded_kb, tmp_path):
    """The CLI tells the operator to re-run with --force; that has to work."""
    await export(session, seeded_kb, tmp_path)
    adr = tmp_path / "docs/adr/0001-use-postgres.md"
    adr.write_text(adr.read_text() + "\nMine.\n")

    entry = await q_kb.get_entry_by_slug(session, "use-postgres", type="decision")
    await q_kb.set_status(session, entry.id, "archived")
    await session.flush()

    result = await export(session, seeded_kb, tmp_path, force=True)
    assert result.conflicts == []
    assert not adr.exists()


async def test_unreadable_target_is_a_conflict_not_a_crash(
    session, seeded_kb, tmp_path
):
    (tmp_path / CONTEXT).write_bytes(b"\xff\xfe not utf-8 \x00")
    result = await export(session, seeded_kb, tmp_path)
    assert CONTEXT in result.conflicts
    # the rest of the run still completed
    assert (tmp_path / "docs/adr/0001-use-postgres.md").is_file()


async def test_two_entries_rendering_to_one_path_are_refused(
    session, repo, tmp_path
):
    """entries_for_export dedupes on title, but filenames come from slug."""
    await q_kb.create_entry(
        session, "Auth flow", "the global one", type="specification", slug="auth-flow"
    )
    await q_kb.create_entry(
        session,
        "Auth flow (acme)",
        "the repo one",
        type="specification",
        slug="auth-flow",
        repository_id=repo.id,
    )
    await session.flush()

    result = await export(session, repo, tmp_path)
    assert any("share this slug" in f["error"] for f in result.failed)
    assert not (tmp_path / "docs/spec/auth-flow.md").exists()


# ---- the CLI shell (review finding 19) -----------------------------------


class _FixedSessionmaker:
    """Hands amain the test session instead of opening its own engine."""

    def __init__(self, session):
        self._session = session

    def __call__(self):
        return self

    async def __aenter__(self):
        return self._session

    async def __aexit__(self, *exc):
        return False


@pytest.fixture
def cli(session, monkeypatch):
    from cartograph.kb.export import __main__ as cli_main

    monkeypatch.setattr(cli_main, "get_sessionmaker", lambda: _FixedSessionmaker(session))

    async def run(*argv):
        return await cli_main.amain(cli_main.build_parser().parse_args(list(argv)))

    return run


async def test_cli_unknown_repo_exits_2(cli, tmp_path):
    assert await cli("--repo", "nope", "--out", str(tmp_path)) == 2


async def test_cli_missing_out_directory_exits_2(cli, seeded_kb, tmp_path):
    assert await cli("--repo", "acme", "--out", str(tmp_path / "nope")) == 2


async def test_cli_clean_run_exits_0(cli, seeded_kb, tmp_path):
    assert await cli("--repo", "acme", "--out", str(tmp_path)) == 0
    assert (tmp_path / CONTEXT).is_file()


async def test_cli_conflict_exits_3(cli, seeded_kb, tmp_path):
    (tmp_path / CONTEXT).write_text("# mine\n")
    assert await cli("--repo", "acme", "--out", str(tmp_path)) == 3


async def test_cli_unhandled_exception_exits_1(cli, seeded_kb, tmp_path, monkeypatch):
    from cartograph.kb.export import __main__ as cli_main

    async def boom(*args, **kwargs):
        raise RuntimeError("rendering blew up")

    monkeypatch.setattr(cli_main, "run_export", boom)
    assert await cli("--repo", "acme", "--out", str(tmp_path)) == 1


async def test_cli_out_defaults_to_the_repository_root(cli, session, tmp_path):
    from cartograph.query import ingest as q_ingest

    repository = await q_ingest.upsert_repository(session, "rooted", str(tmp_path))
    await q_kb.create_entry(session, "PSN", "PositageNet", repository_id=repository.id)
    await session.flush()

    assert await cli("--repo", "rooted") == 0
    assert (tmp_path / CONTEXT).is_file()
