"""The KB type layer — pure, no database."""

import random
from pathlib import PurePosixPath

import pytest
from pydantic import ValidationError

from cartograph.kb.types import (
    LOOKUP_PRECEDENCE,
    REGISTRY,
    Decision,
    Glossary,
    UnknownKbTypeError,
    get_type,
    type_rank,
    types_with_lookup_key,
)
from cartograph.kb.types.base import LOOKUP_KEYS
from conftest import make_view


# ---- registry ------------------------------------------------------------


def test_registry_names_match_keys():
    assert all(name == kb_type.name for name, kb_type in REGISTRY.items())
    assert set(REGISTRY) == set(LOOKUP_PRECEDENCE)


def test_registry_lookup_keys_are_valid():
    for kb_type in REGISTRY.values():
        assert kb_type.lookup_keys
        assert set(kb_type.lookup_keys) <= set(LOOKUP_KEYS)


def test_every_type_exports_relative_paths(ctx):
    for name, kb_type in REGISTRY.items():
        view = make_view(name, "sample", "Sample", seq=1)
        for path in kb_type.export([view], ctx):
            assert not path.is_absolute()
            assert ".." not in path.parts


def test_unknown_type_raises():
    with pytest.raises(UnknownKbTypeError) as exc:
        get_type("adr")
    assert "adr" in str(exc.value)


def test_types_with_lookup_key_is_precedence_ordered():
    assert types_with_lookup_key("aliases") == ("glossary", "convention")
    assert type_rank("glossary") == 0
    assert type_rank("nope") == len(LOOKUP_PRECEDENCE)


# ---- embed text ----------------------------------------------------------


def test_glossary_embed_text_matches_legacy_format():
    """The pre-typed-KB f-string, byte for byte.

    If this changes, every embedding written before the typed-KB migration is
    silently invalidated and has to be re-paid for at Voyage.
    """
    view = make_view("glossary", "psn", "PSN", "PositageNet")
    assert Glossary.embed_text(view) == "PSN: PositageNet"
    assert Glossary.embed_text(view) == f"{view.title}: {view.body}"


def test_decision_embed_text_includes_context_and_consequences():
    view = make_view(
        "decision",
        "flat-threads",
        "Flat threads",
        "Re-parent replies to the root.",
        payload={"context": "Threads nested arbitrarily.", "consequences": "Two levels only."},
        seq=1,
    )
    text = Decision.embed_text(view)
    assert "Threads nested arbitrarily." in text
    assert "Two levels only." in text
    assert text != f"{view.title}: {view.body}"


# ---- payload validation --------------------------------------------------


@pytest.mark.parametrize("name", sorted(REGISTRY))
def test_payload_rejects_unknown_keys(name):
    with pytest.raises(ValidationError):
        REGISTRY[name].validate_payload({"definitely_not_a_field": 1})


@pytest.mark.parametrize("name", sorted(REGISTRY))
def test_payload_defaults_are_empty(name):
    assert isinstance(REGISTRY[name].validate_payload(None), dict)


def test_payload_fields_describes_the_shape():
    fields = Decision.payload_fields()
    assert "context" in fields
    assert "optional" in fields["context"]


def test_decision_rejects_bad_status():
    with pytest.raises(ValidationError):
        Decision.validate_payload({"decision_status": "maybe"})


# ---- glossary export -----------------------------------------------------


def glossary_entries():
    return [
        make_view(
            "glossary",
            "order",
            "Order",
            "A customer's request for goods.",
            payload={"avoid": ["Purchase", "transaction"]},
        ),
        make_view("glossary", "invoice", "Invoice", "A request for payment.", entry_id=2),
    ]


def test_glossary_export_pocock_format(ctx):
    [(path, content)] = Glossary.export(glossary_entries(), ctx).items()
    assert path == PurePosixPath("CONTEXT.md")
    assert content.startswith("<!-- generated by cartograph;")
    assert "# Acme" in content
    assert "## Language" in content
    assert "**Order**:\nA customer's request for goods.\n_Avoid_: Purchase, transaction" in content


def test_glossary_export_omits_avoid_line_when_empty(ctx):
    [content] = Glossary.export(glossary_entries(), ctx).values()
    invoice = content.split("**Invoice**:")[1]
    assert "_Avoid_" not in invoice


def test_glossary_export_is_stable_and_order_independent(ctx):
    entries = glossary_entries()
    baseline = Glossary.export(sorted(entries, key=Glossary.sort_key), ctx)
    for _ in range(5):
        shuffled = entries[:]
        random.shuffle(shuffled)
        assert Glossary.export(sorted(shuffled, key=Glossary.sort_key), ctx) == baseline


# ---- other types ---------------------------------------------------------


def test_decision_export_filename_is_zero_padded(ctx):
    view = make_view("decision", "use-postgres", "Use Postgres", seq=1)
    [path] = Decision.export([view], ctx)
    assert path == PurePosixPath("docs/adr/0001-use-postgres.md")


def test_decision_export_renders_status_and_consequences(ctx):
    view = make_view(
        "decision",
        "use-postgres",
        "Use Postgres",
        "We use Postgres.",
        payload={
            "decision_status": "superseded",
            "context": "We needed a database.",
            "consequences": "One dependency.",
            "deciders": ["john"],
        },
        seq=7,
    )
    [content] = Decision.export([view], ctx).values()
    assert "# 0007. Use Postgres" in content
    assert "- Status: superseded" in content
    assert "- Deciders: john" in content
    assert "## Context\n\nWe needed a database." in content
    assert "## Consequences\n\nOne dependency." in content


def test_decision_sorts_by_seq_not_title(ctx):
    late = make_view("decision", "aaa", "AAA", seq=9)
    early = make_view("decision", "zzz", "ZZZ", seq=1, entry_id=2)
    assert sorted([late, early], key=Decision.sort_key) == [early, late]


def test_decision_without_seq_is_a_loud_error(ctx):
    with pytest.raises(ValueError, match="no seq"):
        Decision.export([make_view("decision", "x", "X")], ctx)


def test_specification_export_one_file_per_entry(ctx):
    spec = REGISTRY["specification"]
    views = [
        make_view("specification", "board", "Board protocol", payload={"requirements": ["A", "B"]}),
        make_view("specification", "ingest", "Ingest", entry_id=2),
    ]
    out = spec.export(views, ctx)
    assert set(out) == {
        PurePosixPath("docs/spec/board.md"),
        PurePosixPath("docs/spec/ingest.md"),
    }
    assert "- A\n- B" in out[PurePosixPath("docs/spec/board.md")]


def test_runbook_export_numbers_steps(ctx):
    view = make_view(
        "runbook",
        "rotate-key",
        "Rotate the Voyage key",
        payload={"steps": ["Revoke", "Issue", "Redeploy"], "severity": "high"},
    )
    [content] = REGISTRY["runbook"].export([view], ctx).values()
    assert "- Severity: high" in content
    assert "1. Revoke\n2. Issue\n3. Redeploy" in content


def test_convention_export_renders_examples(ctx):
    view = make_view(
        "convention",
        "branch-names",
        "Branch names",
        payload={
            "applies_to": ["*"],
            "rationale": "main is protected.",
            "examples": [{"good": "main.feature", "bad": "feature", "note": "Always prefix."}],
        },
    )
    [content] = REGISTRY["convention"].export([view], ctx).values()
    assert "## Rationale\n\nmain is protected." in content
    assert "Do:" in content and "main.feature" in content
    assert "Avoid:" in content and "Always prefix." in content


@pytest.mark.parametrize("name", sorted(REGISTRY))
def test_export_files_end_with_exactly_one_newline(ctx, name):
    view = make_view(name, "sample", "Sample", seq=1)
    for content in REGISTRY[name].export([view], ctx).values():
        assert content.endswith("\n")
        assert not content.endswith("\n\n")


# ---- lint ----------------------------------------------------------------


def test_glossary_lints_an_over_long_definition():
    short = make_view("glossary", "psn", "PSN", "PositageNet. Never anything else.")
    assert Glossary.validate_entry(short) == []
    rambling = make_view("glossary", "psn", "PSN", "One. Two. Three. Four.")
    assert Glossary.validate_entry(rambling)
